# ตั้งค่าการ build และ deploy
[build]
  # โฟลเดอร์ที่มีไฟล์ static
  publish = "public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 